repos:
  - repo: https://github.com/asottile/pyupgrade
    rev: v3.11.0
    hooks:
      - id: pyupgrade
        args: ["--py38-plus"]
  - repo: https://github.com/asottile/reorder_python_imports
    rev: v3.11.0
    hooks:
      - id: reorder-python-imports
  - repo: https://github.com/psf/black
    rev: 23.9.1
    hooks:
      - id: black
  - repo: https://github.com/PyCQA/flake8
    rev: 6.1.0
    hooks:
      - id: flake8
        additional_dependencies: [flake8-bugbear]
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: check-byte-order-marker
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
  - repo: local
    hooks:
      - id: rst
        name: rst
        entry: rst-lint --encoding utf-8
        files: ^(README.rst)$
        language: python
        additional_dependencies: [pygments, restructuredtext_lint]
